CREATE TABLE PROFESSORES 
(
CODIGO INT NOT NULL PRIMARY KEY,
NOME VARCHAR2(30) NOT NULL, 
ESCOLA VARCHAR2(60) NOT NULL, 
NUMERO NUMBER, 
DISCIPLINA VARCHAR2(3) NOT NULL REFERENCES DISCIPLINAS (CODIGO)
);