CREATE OR REPLACE FUNCTION FNC_CALC_HH

(P_DTINI DATE, P_DTFIM DATE)

RETURN NUMBER /*RETORNA O RESULTADO DE 10 VEZES O VALOR DO PARÂMETRO*/

/*INÍCIO DA DEFINIÇÃO DA FUNÇÃO*/
AS

/*VARIÁVEL PARA ARMAZENAR O RESULTADO*/
V_RESULTADO NUMBER;

/*INÍCIO DO BLOCO DE CÓDIGOS*/
BEGIN

/*ARMAZENA O RESULTADO*/
--V_RESULTADO := 10 * P_HORAS;

V_RESULTADO := (P_DTFIM - P_DTINI) * 24;

/*RETORNA O RESULTADO*/
RETURN V_RESULTADO; 

/*FIM DO BLOCO DE CÓDIGOS*/
END;
