/*CRIA OU ATUALIZA A FUNÇÃO FNC_CALC_HH QUE RECEBE UM PARÂMETRO DO TIPO NUMBER E RETORNA O RESULTADO DE 10 VEZES O VALOR DO PARÂMETRO*/

CREATE OR REPLACE FUNCTION FNC_CALC_HH (P_HORAS NUMBER) RETURN NUMBER /*RETORNA O RESULTADO DE 10 VEZES O VALOR DO PARÂMETRO*/

/*INÍCIO DA DEFINIÇÃO DA FUNÇÃO*/
AS

/*VARIÁVEL PARA ARMAZENAR O RESULTADO*/
V_RESULTADO NUMBER;

/*INÍCIO DO BLOCO DE CÓDIGOS*/
BEGIN

/*ARMAZENA O RESULTADO*/
V_RESULTADO := 10 * P_HORAS;

/*RETORNA O RESULTADO*/
RETURN V_RESULTADO; 

/*FIM DO BLOCO DE CÓDIGOS*/
END;