INSERT INTO aluno (codigo, nome, idade, turma) VALUES (1, 'Gabriel Souza', 13, '701MAT');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (2, 'Ana Beatriz Lima', 13, '702MAT');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (3, 'Lucas Oliveira', 14, '801MAT');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (4, 'Maria Eduarda Santos', 14, '802VES');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (5, 'Pedro Henrique Costa', 15, '901MAT');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (6, 'Isabela Ferreira', 15, '902VES');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (7, 'Matheus Almeida', 15, '101INFO');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (8, 'Sophia Rodrigues', 16, '102LOG');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (9, 'Guilherme Pereira', 16, '104LOG');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (10, 'Laura Martins', 16, '106INFO');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (11, 'Rafael Carvalho', 16, '201SST');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (12, 'Julia Gomes', 17, '201EDF');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (13, 'Bruno Ribeiro', 17, '202INFO');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (14, 'Beatriz Barbosa', 17, '301POR');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (15, 'Enzo Araújo', 18, '302EDF');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (16, 'Manuela Dias', 13, '701MAT');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (17, 'Miguel Nascimento', 13, '702MAT');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (18, 'Alice Monteiro', 14, '801MAT');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (19, 'Davi Cardoso', 14, '802VES');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (20, 'Valentina Teixeira', 15, '901MAT');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (21, 'Arthur Correia', 15, '902VES');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (22, 'Lorena Pinto', 15, '101INFO');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (23, 'Heitor Moreira', 16, '102LOG');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (24, 'Yasmin Cavalcante', 16, '104LOG');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (25, 'Theo Rocha', 16, '106INFO');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (26, 'Helena Batista', 16, '201SST');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (27, 'Bernardo Freitas', 17, '201EDF');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (28, 'Livia Nunes', 17, '202INFO');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (29, 'Vinicius Machado', 17, '301POR');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (30, 'Larissa Reis', 18, '302EDF');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (31, 'Gustavo Azevedo', 13, '701MAT');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (32, 'Camila Vieira', 13, '702MAT');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (33, 'Felipe Duarte', 14, '801MAT');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (34, 'Amanda Farias', 14, '802VES');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (35, 'Leonardo Campos', 15, '901MAT');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (36, 'Bianca Xavier', 15, '902VES');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (37, 'Caio Fonseca', 15, '101INFO');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (38, 'Fernanda Melo', 16, '102LOG');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (39, 'João Vitor Tavares', 16, '104LOG');
INSERT INTO aluno (codigo, nome, idade, turma) VALUES (40, 'Rebeca Andrade', 16, '106INFO');
