
  CREATE TABLE PROFESSORES 
   (	CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR2(30) NOT NULL ENABLE, 
	ESCOLA VARCHAR2(60), 
	NUMERO NUMBER, 
	DISCIPLINA VARCHAR2(3) NOT NULL REFERENCES DISCIPLINAS (CODIGO)
   ) ;